stages:
  - cleanup
  - test
  - deploy

# TODO test

deploy_staging:
  stage: deploy
  variables:
    SOURCE_BRANCH: master
    TARGET_HOST: staging
  only:
  - staging
  - master
  trigger: Openki/sysadmin/deploy-config

deploy_prod:
  stage: deploy
  variables:
    SOURCE_BRANCH: master
    TARGET_HOST: live
  only:
  - master
  trigger: Openki/sysadmin/deploy-config
